### ISSUE TITLE
Item content is not displayed correctly

### ISSUE THREAD

**Issue by petersm05** [sasauz/kibana_vis_gantt#2]
Attached file is created based on this data:
{
"name" : "Bank System",
"lifeCycle": [{
			"startlc": "2017-02-02",
			"endlc": "2017-05-05",
			"stagelc": "Phase 2"
		},
		{
			"startlc": "2017-05-06",
			"endlc": "2017-08-08",
			"stagelc": "Phase 2"
		}
	]

}

As you can see in the attached file I only see labels for phase 1. What you cannot see in the attached file is that the first phase 1 runs until the endlc of phase 2.

![screen shot 2017-11-10 at 15 05 34](https://user-images.githubusercontent.com/2598878/32661963-23261f78-c629-11e7-958a-feefa277cb5b.png)

**Comment by sasauz** [comment]
I will loock your case in next days.

**Comment by sasauz** [comment]
I found the problem. Unfortunately the problem is not with gantt plugin. Kibana has generally problem with JSON-structure which you are using. Here is how I found it.
1. I've created 3 JSONs
![image](https://user-images.githubusercontent.com/897489/32781431-51c20378-c945-11e7-9d53-548aef70aa3d.png)
2. Create table with columns (name, lifeCycle.startlc, lifeCycle.endlc and lifeCycle.stagelc). You will see that instead of 6 rows Kibana shows 16 rows.:
![image](https://user-images.githubusercontent.com/897489/32781462-6f37ce1a-c945-11e7-84de-aedc726e43d8.png)

Its means that Kibana can't work with your JSON structure. You can try to create an issue by Elastic\Kibana. 

Or if you can save your data in other JSON-format, for example: 
```
{"name" : "Bank System",
"lifeCycle_startlc": "2017-02-02",
"lifeCycle_endlc": "2017-05-05",
"lifeCycle_stagelc": "Phase 2"
},
{"name" : "Bank System",
"lifeCycle_startlc": "2017-05-06",
"lifeCycle_endlc": "2017-08-08",
"lifeCycle_stagelc": "Phase 2"
}
```
then it should work fine.

**Comment by petersm05** [comment]
Hi,

Thank you for your answer. Will try to work with the new format.

Mark

**Comment by sasauz** [comment]
Hi Mark,

you are welcome! :) By the way, I've update the plugin. You will find, how to update plugin in re-install part in description.

Aleks
